program ::= { struct } { fn } { statement } exit_stmt
struct ::= "struct" ident NL "{" NL field_decl { field_decl } "}" NL
field_decl ::= type [ "mut" ] ident NL
fn ::= "fn" ident ":=" "(" [ type ident { "," type ident } ] ")" "->" type NL block
statement ::= decl | assign | if | while
decl ::= type [ "mut" ] ident init
init ::= "{" value { "," value } "}"
value ::= expr | init
type ::= "i32" | "i64" | "bool" | ident
assign ::= ident { "." ident } ":=" expr
if ::= "if" expr NL block [ "else" NL block ]
while ::= "while" expr NL block
block ::= "{" NL { statement } [ exit_stmt NL ] "}" NL
exit_stmt ::= "exit" factor
expr ::= arith [ ( "==" | "!=" ) arith ]
arith ::= term { ( "+" | "-" ) term }
term ::= factor { "*" factor }
factor ::= number | "true" | "false" | ident | field | call | "!" factor
field ::= ident "." ident { "." ident }
call ::= ident "(" [ expr { "," expr } ] ")"
